name: goto
description: Goto keeps a key-value record of paths you wish to save for quick access later.
version: 0.2.0
homepage: https://github.com/predatorx7/goto
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  path: ^1.9.0
  args: ^2.7.0
  colorize: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.6.0
